FROM ubuntu-document-bench:24.04-linuxarm64

COPY pdf_accel.py /usr/local/lib/python3.12/dist-packages/pdf_accel.py
COPY pdf_accel.pth /usr/local/lib/python3.12/dist-packages/pdf_accel.pth

RUN python3 -c "import pdf_accel; print('pdf_accel installed')"
